spring:
  application:
    name: lottery-draw-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/lottery_draw_db}
    username: ${DATABASE_USER:postgre_user}
    password: ${DATABASE_PASSWORD:postgre_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: ${SMTP_HOST:smtp.ethereal.email}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:lizeth.boehm@ethereal.email}
    password: ${SMTP_PASSWORD:VwCannYz3BSBPptXrd}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: false


app:
  jwt:
    secret: mephi
    token-expiration-milliseconds: 3600000